### ISSUE TITLE
Reids连接异常

### ISSUE THREAD

**Issue by yintao666** [IKende/BeetleX.Redis#19]
K哥,最近我们线上Redis偶发性异常,在正式服务器连接Redis的时候发生"Unable to cast object of type 'System.String' to type 'System.Int64'",在发生异常的同时本地环境连接线上Redis一切正常,有点摸不着头脑....

**Comment by beetlex-io** [comment]
应该是某个指令响应的数据格式不对

**Comment by yintao666** [comment]
嗯  看报错来看确实是这样,可是所有相应的数据格式都是和存放时一致,而且就连Redis.Exists返回值都报这个错,我想是否是Redis返回了什么报错信息,为字符串,导致转long失败了。

**Comment by yintao666** [comment]
当报这个错时候,只有某个服务器上的所有客户端连接会这样,其他服务器的客户端则能正常读写,有点诡异.

**Comment by beetlex-io** [comment]
建议输出代码栈，否则无法知道具体位置

**Comment by yintao666** [comment]
我这边有一些跟踪,我去copy一下,K哥稍等

**Comment by yintao666** [comment]
2020-08-28 17:25:15,645 ERROR InfoLogger - Redis连接错误:Unable to cast object of type 'System.String' to type 'System.Int64'.
2020-08-28 17:25:15,927 ERROR InfoLogger - 异常消息:Unable to cast object of type 'System.Int64' to type 'System.String'.
异常跟踪:   at BeetleX.Redis.RedisDB.Get[T](String key) in F:\Work\App\Cache.BeetleRedis\RedisDB.cs:line 300
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at BeetleX.Redis.Redis.Get[T](String key) in F:\Work\App\Cache.BeetleRedis\Redis.cs:line 117
   at Core.SqlDbCore.Task.RewardSqlDbCore.NewGetSuperTopTaskList(Boolean hideTask) in F:\Work\App\SqlDbCore\Task\RewardSqlDbCore.cs:line 1453
   at Core.LogicSever.Task.RewardService.NewGetSuperTopTaskList(Boolean hideTask) in F:\Work\App\LogicSever\Task\RewardService.cs:line 2260
   at (Object , Object[] )
   at BeetleX.FastHttpApi.ActionContext.OnExecute(IActionResultHandler resultHandler)



2020-08-28 17:25:20,261 ERROR InfoLogger - 异常消息:Unable to cast object of type 'System.String' to type 'System.Int64'.
异常跟踪:   at BeetleX.Redis.RedisDB.Exists(String[] key) in F:\Work\App\Cache.BeetleRedis\RedisDB.cs:line 229
   at BeetleX.Redis.Redis.Exists(String[] key) in F:\Work\App\Cache.BeetleRedis\Redis.cs:line 77
   at CacheCore.CacheBase`1.GetList() in F:\Work\App\CacheCore\CacheBase.cs:line 61
   at Core.LogicSever.Sys.NoticeService.GetNoticeEntities() in F:\Work\App\LogicSever\Sys\NoticeService.cs:line 23
   at ApiService.Controllers.Sys.NoticeController.GetNotices() in F:\Work\App\ApiServer\Controllers\Sys\NoticeController.cs:line 30
   at BeetleX.FastHttpApi.ActionContext.OnAsyncExecute(IActionResultHandler resultHandler)



2020-08-28 17:25:21,926 ERROR InfoLogger - 异常消息:Unable to cast object of type 'System.Int64' to type 'System.String'.
异常跟踪:   at BeetleX.Redis.RedisHashTable.<>c.<Keys>b__24_0(ResultItem a) in F:\Work\App\Cache.BeetleRedis\HashTable.cs:line 135
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BeetleX.Redis.RedisHashTable.Keys() in F:\Work\App\Cache.BeetleRedis\HashTable.cs:line 135
   at CacheCore.CacheBase`1.GetList() in F:\Work\App\CacheCore\CacheBase.cs:line 64
   at Core.LogicSever.Sys.AppVersionService.Upgrade(String verSion, String pkgName, String channel, Boolean checkRunType) in F:\Work\App\LogicSever\Sys\AppVersionService.cs:line 78
   at ApiService.Controllers.SysBase.AppVersionController.CheckVersion(String version, String pkgName, String channel) in F:\Work\App\ApiServer\Controllers\SysBase\AppVersionController.cs:line 66
   at BeetleX.FastHttpApi.ActionContext.OnAsyncExecute(IActionResultHandler resultHandler)

**Comment by yintao666** [comment]
我都尝试了查找错误根源
public async ValueTask<long> Exists(params string[] key)
        {
            Commands.EXISTS exists = new Commands.EXISTS(key);
            var result = await Execute(exists, typeof(string));
            if (result.IsError)
                throw new RedisException(result.Messge);
            return (long)result.Value;
        }
这后面的long转换出错了,咱们源码中很多这种强转,我查看了传入Type的源码部分,K哥你有做type的is判断,也有相应处理,这才来麻烦K哥,我感觉我每周都在麻烦你...sry

**Comment by beetlex-io** [comment]
其实redis每个指令都有固定的内容返回，可能新版的redis存在这个指令有其他内容返回的可能性，建议直接挂上源码加个内容输出。

**Comment by yintao666** [comment]
我昨晚在源码上挂上了日志，等下次遇到的时候行再进行捕捉一下具体内容，对了k哥，你那边用的啥版本呢？

**Comment by yintao666** [comment]
k哥,我在返回值那写了一个捕捉的方法,然后运用到您的源码中,捕捉到一些日志
 
 //异常捕捉器
private Func<Func<long>, Action, long> ConversionCapture = new Func<Func<long>, Action, long>((Func<long> func, Action action) =>
           {
               try
               {
                   return func();
               }
               catch (Exception ex)
               {
                   action.Invoke();
                   return 0;
               }
           });


  public async ValueTask<T> Get<T>(string key)
        {
            Commands.GET cmd = new Commands.GET(key, DataFormater);
            var result = await Execute(cmd, typeof(T));
            if (result.IsError)
                throw new RedisException(result.Messge);
            try
            {
                return (T)result.Value;
            }
            catch (Exception ex)
            {
                Log.Error($"Redis转换异常:result.Value[{result.Value.GetType()}],目标类型:{typeof(T)}");
                return default(T);
            }
        }


  public async ValueTask<long> Exists(params string[] key)
        {
            Commands.EXISTS exists = new Commands.EXISTS(key);
            var result = await Execute(exists, typeof(string));
            if (result.IsError)
                throw new RedisException(result.Messge);
            return ConversionCapture.Invoke(new Func<long>(() =>
             {
                 return (long)result.Value;
             }), new Action(() =>
             {
                 Log.Error($"Redis转换异常:result.Value[{result.Value}],目标类型:long");
             }));
        }


日志:
2020-11-10 23:03:15,438 ERROR InfoLogger - Redis转换异常:result.Value["116949,98272,110042,109933"],目标类型:long
2020-11-10 23:03:15,464 ERROR InfoLogger - Redis错误:Unable to cast object of type 'System.Int64' to type 'System.String'.
2020-11-10 23:03:15,612 ERROR InfoLogger - Redis转换异常:result.Value[],目标类型:long
2020-11-10 23:03:15,621 ERROR InfoLogger - 异常消息:One or more errors occurred. (Unable to cast object of type 'System.Int64' to type 'System.String'.)
内部异常:Unable to cast object of type 'System.Int64' to type 'System.String'.
异常跟踪:   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ApiService.Controllers.Tasks.NewTaskController.GetTaskDetail(IHttpContext httpContext, Int64 userId, Int64 taskRewardId) in E:\111\ApiServer\Controllers\Tasks\NewTaskController.cs:line 298
   at BeetleX.FastHttpApi.ActionContext.OnAsyncExecute(IActionResultHandler resultHandler)
2020-11-10 23:03:15,639 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:15,690 ERROR InfoLogger - Redis转换异常:result.Value[2598],目标类型:long
2020-11-10 23:03:15,793 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"190511","nickname":"A扫我头像二维码","account":"15706672484","isSdkService":false}],目标类型:long
2020-11-10 23:03:20,833 ERROR InfoLogger - Redis错误:Unable to cast object of type 'System.Int64' to type 'System.String'.
2020-11-10 23:03:21,071 ERROR InfoLogger - Redis转换异常:result.Value[],目标类型:long
2020-11-10 23:03:21,567 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:21,591 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"156225","nickname":"执念","account":"15597209710","isSdkService":false}],目标类型:long
2020-11-10 23:03:22,513 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:22,628 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:22,767 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"233800","nickname":"赚友","account":"17390470373","isSdkService":false}],目标类型:long
2020-11-10 23:03:22,771 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"234127","nickname":"赚友","account":"15022590932","isSdkService":false}],目标类型:long
2020-11-10 23:03:22,938 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:23,330 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"188522","nickname":"承诺","account":"15207917727","isSdkService":false}],目标类型:long
2020-11-10 23:03:23,421 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:23,824 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"230195","nickname":"赚友","account":"13028672153","isSdkService":false}],目标类型:long
2020-11-10 23:03:23,958 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:Core.Model.TokenUserInfo
2020-11-10 23:03:24,498 ERROR InfoLogger - Redis转换异常:result.Value[{"userId":"234114","nickname":"赚友","account":"15346995244","isSdkService":false}],目标类型:long
2020-11-10 23:03:24,501 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:System.String


偶发性的,并不会每天都出现,频率一般为3天左右,还不知道怎么处理,还请K哥救急.

**Comment by yintao666** [comment]
最新日志是从这里开始的 K哥

2020-11-10 23:03:15,195 ERROR InfoLogger - Redis连接错误:ERR unknown command 'ISTS'
2020-11-10 23:03:15,311 ERROR InfoLogger - 异常消息:ERR unknown command '$15'
异常跟踪:   at BeetleX.Redis.RedisDB.Exists(String[] key) in E:\111\Cache.BeetleRedis\RedisDB.cs:line 261
   at BeetleX.Redis.Redis.Exists(String[] key) in E:\111\Cache.BeetleRedis\Redis.cs:line 78
   at CacheCore.CacheBase`1.GetList() in E:\111\CacheCore\CacheBase.cs:line 61
   at Core.LogicSever.Sys.NotifyService.GetNotifyEntities(Int32 type) in E:\111\LogicSever\Sys\NotifyService.cs:line 30
   at ApiService.Controllers.Sys.NotifyController.GetNotifys() in E:\111\ApiServer\Controllers\Sys\NotifyController.cs:line 36
   at BeetleX.FastHttpApi.ActionContext.OnAsyncExecute(IActionResultHandler resultHandler)
2020-11-10 23:03:15,313 ERROR InfoLogger - Redis连接错误:ERR unknown command 'Forbidden215962'
2020-11-10 23:03:15,323 ERROR InfoLogger - Redis转换异常:result.Value[System.Int64],目标类型:System.String

**Comment by beetlex-io** [comment]
你们有的redis版本是多少，把你们的使用代码和相关指令提交一下上来

**Comment by yintao666** [comment]
我们用的Redis版本是windows版 3.2.100,采用1读一写的方式,然后K哥我把所用到的redis和简单源码传上来啦

[Redis.zip](https://github.com/IKende/BeetleX.Redis/files/5522036/Redis.zip)

[SmapleApp.zip](https://github.com/IKende/BeetleX.Redis/files/5522037/SmapleApp.zip)

**Comment by beetlex-io** [comment]
初步定位是连接池问题。

**Comment by yintao666** [comment]
嗯嗯，那还麻烦k哥喽，因为我们最近服务器从8核降2核后发生的频率就基本一天一次了，每次重启了服务就好了。

**Comment by beetlex-io** [comment]
可尝试更新最新版本
`Redis.Default` 对应是`DefaultRedis.Instance`
